// 常用西藥（以台灣藥局可購得之成藥／指示藥為主）
// dose 為成人一般標示用量，實際請依產品仿單與藥師指示
window.WEST_MEDS = [
  // ── 止痛退燒 ──
  { id:"apap", atc:"N02BE01", name:"乙醯胺酚", en:"Acetaminophen (Paracetamol)", cls:"止痛退燒", brand:"普拿疼、斯斯解痛錠、多數綜合感冒藥內含",
    use:"發燒、頭痛、牙痛、經痛、肌肉痛等輕中度疼痛；不傷胃，孕婦相對安全的首選止痛藥",
    dose:"500 mg 1–2 錠，每 4–6 小時一次；每日上限 4,000 mg（常喝酒或肝病者建議 ≤2,000 mg）",
    caution:"過量會造成嚴重肝損傷；綜合感冒藥多已含本成分，勿重複服用；服藥期間避免飲酒",
    tag:["成藥","指示藥"] },
  { id:"ibu", atc:"M01AE01", name:"布洛芬", en:"Ibuprofen", cls:"止痛退燒（NSAID）", brand:"伊普、Advil、EVE",
    use:"經痛、牙痛、肌肉關節痛、發炎性疼痛、發燒；消炎效果優於乙醯胺酚",
    dose:"200–400 mg，每 6–8 小時一次，飯後服用；自行用藥每日上限 1,200 mg",
    caution:"傷胃，胃潰瘍、胃出血病史者避免；腎功能不良、氣喘（阿斯匹靈過敏）者慎用；懷孕後期（≥20 週）禁用；不可與其他 NSAID 併用",
    tag:["指示藥"] },
  { id:"naproxen", atc:"M01AE02", name:"那普洛先", en:"Naproxen", cls:"止痛退燒（NSAID）", brand:"Aleve、舒痛寧",
    use:"經痛、肌肉關節痛、扭傷；藥效較長（8–12 小時）",
    dose:"220–250 mg，每 8–12 小時一次，飯後服用；自行用藥每日上限約 660 mg",
    caution:"注意事項同布洛芬；胃腸、腎臟、心血管疾病者慎用",
    tag:["指示藥"] },
  { id:"aspirin", atc:"N02BA01", name:"阿斯匹靈", en:"Aspirin", cls:"止痛退燒（NSAID）", brand:"阿斯匹靈",
    use:"成人頭痛、肌肉痛（止痛用途現較少使用）",
    dose:"325–650 mg，每 4–6 小時一次，飯後服用",
    caution:"18 歲以下發燒（特別是流感、水痘）禁用，恐引起雷氏症候群；易胃出血；服抗凝血藥者勿自行使用",
    tag:["指示藥"] },

  // ── 抗過敏 ──
  { id:"loratadine", atc:"R06AX13", name:"氯雷他定", en:"Loratadine", cls:"抗組織胺（第二代）", brand:"開瑞坦 Clarityne",
    use:"過敏性鼻炎（打噴嚏、流鼻水、鼻癢）、蕁麻疹、皮膚過敏搔癢；較不嗜睡",
    dose:"10 mg，每日一次",
    caution:"少數人仍會輕微嗜睡；肝功能不良者減量",
    tag:["指示藥"] },
  { id:"cetirizine", atc:"R06AE07", name:"西替利嗪", en:"Cetirizine", cls:"抗組織胺（第二代）", brand:"驅異樂 Zyrtec",
    use:"過敏性鼻炎、蕁麻疹、皮膚過敏搔癢；作用快",
    dose:"10 mg，每日一次（睡前服用可減少嗜睡影響）",
    caution:"比 loratadine 稍易嗜睡；開車、操作機械前注意；腎功能不良者減量",
    tag:["指示藥"] },
  { id:"fexofenadine", atc:"R06AX26", name:"非索非那定", en:"Fexofenadine", cls:"抗組織胺（第二代）", brand:"艾來 Allegra",
    use:"過敏性鼻炎、蕁麻疹；幾乎不嗜睡，適合需開車或工作者",
    dose:"60 mg 每日兩次，或 180 mg 每日一次",
    caution:"避免與果汁（柳橙、葡萄柚、蘋果汁）同服，會降低吸收；制酸劑需間隔 2 小時",
    tag:["指示藥"] },
  { id:"cpm", atc:"R06AB04", name:"氯芬尼拉明", en:"Chlorpheniramine (CPM)", cls:"抗組織胺（第一代）", brand:"多數綜合感冒藥、鼻炎藥內含",
    use:"流鼻水、打噴嚏、皮膚癢",
    dose:"4 mg，每 4–6 小時一次；每日上限 24 mg",
    caution:"明顯嗜睡、口乾；青光眼、攝護腺肥大、排尿困難者避免；勿與酒精、安眠藥併用",
    tag:["成藥","指示藥"] },
  { id:"diphenhydramine", atc:"R06AA02", name:"苯海拉明", en:"Diphenhydramine", cls:"抗組織胺（第一代）", brand:"助眠錠、部分止癢藥膏",
    use:"偶發性失眠（短期助眠）、過敏搔癢",
    dose:"助眠：25–50 mg 睡前服用；連續使用勿超過 2 週",
    caution:"隔日可能昏沉；65 歲以上長者易跌倒、意識混亂，不建議；青光眼、攝護腺肥大者避免",
    tag:["指示藥"] },

  // ── 鼻塞、咳嗽、化痰 ──
  { id:"pse", atc:"R01BA02", name:"偽麻黃鹼", en:"Pseudoephedrine", cls:"鼻黏膜血管收縮劑", brand:"綜合感冒藥、鼻炎藥內含",
    use:"鼻塞",
    dose:"60 mg，每 4–6 小時一次；每日上限 240 mg",
    caution:"會使心跳加快、血壓上升、失眠；高血壓、心臟病、甲狀腺亢進、攝護腺肥大者避免；睡前少用",
    tag:["指示藥"] },
  { id:"oxymetazoline", atc:"R01AA", name:"鼻噴劑（去鼻充血）", en:"Oxymetazoline / Xylometazoline", cls:"局部鼻用血管收縮劑", brand:"歐治鼻 Otrivin 等",
    use:"嚴重鼻塞時短期緩解",
    dose:"每鼻孔 1–2 噴，每日 2 次",
    caution:"連續使用勿超過 3–5 天，否則會造成反彈性鼻塞（藥物性鼻炎）",
    tag:["指示藥"] },
  { id:"dxm", atc:"R05DA09", name:"右旋美沙芬", en:"Dextromethorphan (DXM)", cls:"中樞止咳劑", brand:"咳嗽糖漿、綜合感冒藥內含",
    use:"無痰的乾咳",
    dose:"15–30 mg，每 6–8 小時一次；每日上限 120 mg",
    caution:"有痰的咳嗽不宜強行止咳；服用抗憂鬱藥（SSRI、MAOI）者禁止自行併用",
    tag:["成藥","指示藥"] },
  { id:"nac", atc:"R05CB01", name:"乙醯半胱胺酸", en:"Acetylcysteine (NAC)", cls:"化痰劑", brand:"愛克痰、化痰發泡錠",
    use:"痰多黏稠、不易咳出",
    dose:"每日 600 mg（600 mg 一次，或 200 mg 一日三次）；發泡錠溶於水服用",
    caution:"有硫磺味屬正常；氣喘者可能誘發支氣管痙攣；多喝水效果更好",
    tag:["指示藥"] },
  { id:"ambroxol", atc:"R05CB06", name:"安布索", en:"Ambroxol", cls:"化痰劑", brand:"沐舒坦 Mucosolvan",
    use:"痰多黏稠、急慢性支氣管炎的痰液",
    dose:"30 mg，每日三次",
    caution:"孕婦前三個月避免；少數腸胃不適",
    tag:["指示藥"] },
  { id:"bromhexine", atc:"R05CB02", name:"必嗽平", en:"Bromhexine", cls:"化痰劑", brand:"必嗽平 Bisolvon",
    use:"痰多黏稠",
    dose:"8 mg，每日三次",
    caution:"胃潰瘍者慎用；多喝水",
    tag:["指示藥"] },
  { id:"guaifenesin", atc:"R05CA03", name:"愈創木酚甘油醚", en:"Guaifenesin", cls:"祛痰劑", brand:"咳嗽糖漿內含",
    use:"稀釋痰液、幫助咳出",
    dose:"200–400 mg，每 4 小時一次；每日上限 2,400 mg",
    caution:"需多喝水；少數噁心",
    tag:["成藥"] },
  { id:"coldcombo", atc:"R05X", name:"綜合感冒藥", en:"Combination cold remedies", cls:"複方感冒藥", brand:"斯斯、伏冒、普拿疼伏冒等",
    use:"同時有發燒頭痛、鼻塞流鼻水、咳嗽等多種感冒症狀",
    dose:"依產品標示；一般每 4–6 小時一次，每日不超過 4–6 次",
    caution:"通常含乙醯胺酚＋抗組織胺＋鼻塞劑＋止咳劑，勿再另服普拿疼；只有單一症狀時用單方藥較好；高血壓者選不含偽麻黃鹼的配方",
    tag:["成藥","指示藥"] },

  // ── 腸胃 ──
  { id:"antacid", atc:"A02A", name:"制酸劑", en:"Aluminum/Magnesium hydroxide、Calcium carbonate", cls:"制酸劑", brand:"胃乳、吉胃福適、表飛鳴胃腸藥等",
    use:"胃酸過多、火燒心、胃痛不適；作用快但短",
    dose:"症狀出現時或飯後 1 小時及睡前服用；依產品標示",
    caution:"會影響其他藥物吸收（抗生素、鐵劑、甲狀腺素等），需間隔 2 小時；腎功能不良者勿長期使用含鎂、鋁製劑；連續使用勿超過 2 週",
    tag:["成藥"] },
  { id:"famotidine", atc:"A02BA03", name:"法莫替丁", en:"Famotidine", cls:"H2 阻斷劑（抑制胃酸）", brand:"蓋舒泰 Gaster",
    use:"胃酸逆流、火燒心、胃痛；可在吃大餐前預防",
    dose:"10–20 mg，每日 1–2 次",
    caution:"連續使用 2 週未改善應就醫；腎功能不良者減量",
    tag:["指示藥"] },
  { id:"ppi", atc:"A02BC", name:"質子幫浦抑制劑", en:"Omeprazole / Esomeprazole 等", cls:"PPI（強效抑制胃酸）", brand:"部分品項為指示藥",
    use:"頻繁胃酸逆流、火燒心",
    dose:"20 mg，每日一次，早餐前 30–60 分鐘空腹服用；自行使用以 14 天為一療程",
    caution:"非立即止痛，需數天才見效；長期使用應由醫師評估；與 clopidogrel 等藥物有交互作用",
    tag:["指示藥","處方藥"] },
  { id:"simethicone", atc:"A03AX13", name:"二甲基矽油", en:"Simethicone", cls:"消脹氣劑", brand:"加斯克兒、許多胃腸藥內含",
    use:"腹脹、脹氣、打嗝",
    dose:"40–80 mg，飯後及睡前服用（可嚼碎）",
    caution:"幾乎不被吸收，安全性高",
    tag:["成藥"] },
  { id:"loperamide", atc:"A07DA03", name:"洛哌丁胺", en:"Loperamide", cls:"止瀉劑", brand:"樂必寧 Imodium",
    use:"急性非感染性腹瀉（如旅行、飲食不當）",
    dose:"首次 4 mg，之後每次稀便後 2 mg；每日上限 8 mg（自行使用）",
    caution:"發燒、血便、黏液便（疑似細菌感染）時禁用；2 歲以下禁用；腹瀉停止即停藥，勿連用超過 2 天",
    tag:["指示藥"] },
  { id:"ors", atc:"A07CA", name:"口服電解質液", en:"Oral Rehydration Solution (ORS)", cls:"補充水分電解質", brand:"舒適補、寶寶電解水、口服電解質粉",
    use:"腹瀉、嘔吐、中暑造成的脫水；腹瀉時最重要的處置",
    dose:"少量多次小口喝；成人每次稀便後約 200–400 ml",
    caution:"運動飲料糖分高、鈉不足，不能完全取代 ORS（可稀釋一倍應急）",
    tag:["成藥"] },
  { id:"smectite", atc:"A07BC", name:"蒙脫石散", en:"Dioctahedral smectite", cls:"吸附性止瀉劑", brand:"舒腹達 Smecta",
    use:"急性腹瀉，吸附病原與毒素、保護腸黏膜",
    dose:"每包 3 g，每日三次，溶於半杯水",
    caution:"會吸附其他藥物，需間隔 2 小時服用",
    tag:["指示藥"] },
  { id:"probiotic", atc:"A07FA", name:"益生菌／整腸劑", en:"Probiotics", cls:"整腸劑", brand:"表飛鳴、合利他命整腸錠等",
    use:"腹瀉恢復期、便秘、腸道菌叢失調",
    dose:"依產品標示",
    caution:"與抗生素需間隔 2 小時",
    tag:["成藥"] },
  { id:"mgo", atc:"A06AD02", name:"氧化鎂", en:"Magnesium oxide", cls:"緩瀉劑（滲透性）", brand:"氧化鎂錠（俗稱「軟便劑」）",
    use:"便秘；溫和軟便，可長期使用",
    dose:"250–500 mg，每日 2–3 次，配大量開水",
    caution:"腎功能不良者勿用（高血鎂）；會影響抗生素、鐵劑吸收",
    tag:["指示藥"] },
  { id:"bisacodyl", atc:"A06AB02", name:"比沙可啶", en:"Bisacodyl", cls:"緩瀉劑（刺激性）", brand:"樂可舒 Dulcolax",
    use:"偶發便秘，需要較快排便時",
    dose:"5–10 mg，睡前服用（約 6–12 小時後見效）；栓劑 10 mg 15–60 分鐘見效",
    caution:"腸衣錠勿嚼碎，勿與牛奶、制酸劑同服；不可長期使用（易產生依賴）；腹痛原因不明時勿用",
    tag:["指示藥"] },
  { id:"buscopan", atc:"A03BB01", name:"丁基東莨菪鹼", en:"Hyoscine butylbromide", cls:"解痙劑", brand:"寶寇恩 Buscopan",
    use:"腸胃絞痛、腹部痙攣痛、經痛（痙攣性）",
    dose:"10–20 mg，每日 3–4 次",
    caution:"口乾、心跳快、視力模糊；青光眼、攝護腺肥大者避免",
    tag:["指示藥"] },
  { id:"dimenhydrinate", atc:"R06AA11", name:"茶苯海明", en:"Dimenhydrinate", cls:"抗暈動劑", brand:"暈車藥（如 Dramamine）",
    use:"暈車、暈船、暈機；止吐",
    dose:"50–100 mg，出發前 30–60 分鐘服用，每 4–6 小時可重複；每日上限 400 mg",
    caution:"嗜睡；服用後勿開車；青光眼、攝護腺肥大者慎用",
    tag:["成藥","指示藥"] },
  { id:"meclizine", atc:"R06AE05", name:"美克利嗪", en:"Meclizine", cls:"抗暈動劑", brand:"暈車藥（部分品項）",
    use:"暈車、暈船、暈眩；藥效較長（約 24 小時）",
    dose:"25–50 mg，出發前 1 小時服用，每日一次",
    caution:"嗜睡較茶苯海明輕微",
    tag:["指示藥"] },

  // ── 外用 ──
  { id:"hydrocortisone", atc:"D07AA02", name:"氫化可體松乳膏", en:"Hydrocortisone 0.5–1% cream", cls:"外用弱效類固醇", brand:"多數皮膚止癢藥膏",
    use:"濕疹、蚊蟲叮咬、接觸性皮膚炎等紅腫癢",
    dose:"薄擦患處，每日 2–3 次；連續使用勿超過 7 天",
    caution:"勿用於黴菌感染（香港腳、股癬）、細菌感染、傷口；臉部、陰部不宜長期使用",
    tag:["指示藥"] },
  { id:"calamine", atc:"D04A", name:"止癢外用劑", en:"Calamine / Crotamiton / Menthol", cls:"外用止癢劑", brand:"卡拉明液、優力舒 Eurax、曼秀雷敦、綠油精",
    use:"蚊蟲叮咬、皮膚癢、痱子",
    dose:"塗擦患處，每日數次",
    caution:"勿用於破皮、傷口；避開眼睛與黏膜；嬰幼兒避免含樟腦、薄荷腦高濃度製劑",
    tag:["成藥"] },
  { id:"antifungal", atc:"D01AC", name:"抗黴菌乳膏", en:"Clotrimazole / Miconazole / Terbinafine", cls:"外用抗黴菌劑", brand:"克黴唑、達克寧、療黴舒 Lamisil",
    use:"香港腳、股癬、體癬、汗斑",
    dose:"Clotrimazole／Miconazole：每日 2 次，2–4 週；Terbinafine：每日 1–2 次，1–2 週；症狀消失後再多擦 1–2 週",
    caution:"擦藥範圍要超過患處邊緣 2 公分；勿與類固醇藥膏混用；灰指甲外用效果有限應就醫",
    tag:["指示藥"] },
  { id:"diclofenacgel", atc:"M02AA15", name:"外用消炎止痛劑", en:"Diclofenac gel / Methyl salicylate 貼布", cls:"外用 NSAID", brand:"非炎凝膠 Voltaren、撒隆巴斯、痠痛貼布",
    use:"肌肉痠痛、扭傷、關節痛、落枕",
    dose:"凝膠每日 3–4 次塗抹按摩；貼布依標示（多為 8–12 小時一片）",
    caution:"急性扭傷 48 小時內先冰敷；勿用於傷口、濕疹處；對阿斯匹靈過敏或氣喘者慎用；避免同時口服多種 NSAID",
    tag:["成藥","指示藥"] },
  { id:"povidone", atc:"D08AG02", name:"優碘／生理食鹽水", en:"Povidone-iodine / Normal saline", cls:"傷口清潔消毒", brand:"優碘、生理食鹽水",
    use:"小擦傷、割傷的清潔消毒",
    dose:"先以生理食鹽水或清水沖洗，再塗優碘，待乾後以生理食鹽水擦掉殘留，覆蓋紗布或人工皮",
    caution:"甲狀腺疾病、碘過敏者避免大面積使用；大而深的傷口、動物咬傷應就醫",
    tag:["成藥"] },
  { id:"antibioticoint", atc:"D06AX", name:"外用抗生素軟膏", en:"Bacitracin / Neomycin / Fusidic acid", cls:"外用抗生素", brand:"必達舒 Fucidin（處方）、新黴素軟膏",
    use:"小傷口預防感染、輕微毛囊炎",
    dose:"薄擦每日 2–3 次",
    caution:"新黴素較易過敏；勿長期使用；化膿、紅腫擴大應就醫",
    tag:["指示藥","處方藥"] },
  { id:"burncream", atc:"D03", name:"燙傷處理用品", en:"Petrolatum / Hydrogel dressing", cls:"燙傷敷料", brand:"凡士林、燙傷凝膠、人工皮",
    use:"一度燙傷（紅、痛、無水泡）或小水泡的保護",
    dose:"沖冷水降溫後薄擦，覆蓋乾淨紗布",
    caution:"勿塗牙膏、醬油、蘆薈等偏方；水泡勿自行刺破；面積大於手掌、臉部、關節、生殖器燙傷應就醫",
    tag:["成藥"] },
  { id:"oralpaste", atc:"A01AC01", name:"口內膏", en:"Triamcinolone oral paste / 口腔潰瘍貼片", cls:"口腔黏膜用藥", brand:"口內膏（多需處方）、口瘡貼片",
    use:"嘴破、口腔潰瘍疼痛",
    dose:"飯後及睡前擦乾患處後塗一層薄膜，勿塗抹推開",
    caution:"超過 2 週不癒合應就醫排除其他病變",
    tag:["指示藥","處方藥"] },
  { id:"hemorrhoid", atc:"C05A", name:"痔瘡藥膏／栓劑", en:"Lidocaine + Hydrocortisone 等複方", cls:"痔瘡外用藥", brand:"喜療痔、好痔寧、普威痔瘡栓",
    use:"痔瘡腫痛、搔癢、輕微出血",
    dose:"排便後清潔患部，每日 2–3 次塗抹或塞入",
    caution:"連續使用勿超過 7 天；大量出血、持續出血或 45 歲以上首次便血應就醫排除大腸病變",
    tag:["指示藥"] },
  { id:"artificialtears", atc:"S01XA20", name:"人工淚液", en:"Artificial tears", cls:"眼用潤滑劑", brand:"各式人工淚液（建議單支無防腐劑型）",
    use:"眼睛乾澀、疲勞、異物感",
    dose:"每次 1–2 滴，每日 4–6 次",
    caution:"一天使用超過 6 次選無防腐劑型；紅腫疼痛、視力模糊、分泌物多應就醫；勿自行使用含類固醇或抗生素眼藥水",
    tag:["成藥"] },
];
